# Generated by Django 4.2.5 on 2023-10-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_history', '0002_alter_fundhistory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundhistory',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
