# Generated by Django 4.2.5 on 2023-10-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_history', '0003_fundhistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundhistory',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fundhistory',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
