# Generated by Django 4.2.7 on 2023-11-13 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fundtransfer",
            name="checker_assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fund_transfer_checked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fundtransfer",
            name="from_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fund_transfer_from",
                to="account.account",
            ),
        ),
        migrations.AddField(
            model_name="fundtransfer",
            name="to_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fund_transfer_to",
                to="account.account",
            ),
        ),
        migrations.AddField(
            model_name="fundcheck",
            name="approver_assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fund_checked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fundcheck",
            name="fund_transfer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checked_response",
                to="account.fundtransfer",
            ),
        ),
        migrations.AddField(
            model_name="fundcheck",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="fundapprove",
            name="fund_check",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="account.fundcheck"
            ),
        ),
        migrations.AddField(
            model_name="fundapprove",
            name="fund_transfer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_response",
                to="account.fundtransfer",
            ),
        ),
        migrations.AddField(
            model_name="fundapprove",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="account.accounttype"
            ),
        ),
    ]
