# Generated by Django 4.2.5 on 2023-11-16 13:58

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransfer',
            name='transaction_code',
            field=models.CharField(default=secrets.token_hex, max_length=64, unique=True),
        ),
    ]
