# Generated by Django 4.2.5 on 2023-10-08 11:29

from django.db import migrations, models
import django.db.models.deletion
import lib.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_account_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.UUIDField(default=lib.models.create_hex_token, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_from', to='account.account')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_to', to='account.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
