# Generated by Django 4.2.5 on 2023-10-08 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_fundtransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundCheckResponse',
            fields=[
                ('id', models.UUIDField(default=lib.models.create_hex_token, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('is_checked', models.BooleanField()),
                ('fund_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.fundtransfer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundApproveResponse',
            fields=[
                ('id', models.UUIDField(default=lib.models.create_hex_token, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField()),
                ('fund_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.fundtransfer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
