# Generated by Django 4.2.5 on 2023-10-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_fundcheckresponse_fundapproveresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.FloatField(default=0),
        ),
    ]
