# Generated by Django 4.2.5 on 2023-10-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_opening_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundapproveresponse',
            name='fund_transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_response', to='account.fundtransfer'),
        ),
        migrations.AlterField(
            model_name='fundcheckresponse',
            name='fund_transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checked_response', to='account.fundtransfer'),
        ),
    ]
