# Generated by Django 4.2.5 on 2023-10-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_fundtransfer_from_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundapproveresponse',
            name='fund_checking_response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.fundcheckresponse'),
        ),
    ]
