# Generated by Django 4.2.5 on 2023-10-09 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_fundapproveresponse_fund_checking_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FundApproveResponse',
            new_name='FundApprove',
        ),
        migrations.RenameModel(
            old_name='FundCheckResponse',
            new_name='FundCheck',
        ),
    ]
