# Generated by Django 4.2.5 on 2023-10-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_fundapproveresponse_fundapprove_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundapprove',
            name='fund_checking_response',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='account.fundcheck'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundapprove',
            name='fund_transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval_response', to='account.fundtransfer'),
        ),
        migrations.AlterField(
            model_name='fundcheck',
            name='fund_transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='checked_response', to='account.fundtransfer'),
        ),
    ]
