# Generated by Django 4.2.5 on 2023-10-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_fundapprove_fund_checking_response_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundapprove',
            old_name='fund_checking_response',
            new_name='fund_check',
        ),
    ]
