# Generated by Django 4.2.5 on 2023-10-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_fundcheck_approver_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundapprove',
            name='is_2fa_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundcheck',
            name='is_2fa_verified',
            field=models.BooleanField(default=False),
        ),
    ]
