# Generated by Django 4.2.5 on 2023-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_approval_user_user_is_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, help_text='Designates whether the user can add an expense.', verbose_name='author status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_checker',
            field=models.BooleanField(default=False, help_text='Designates whether the user can approve an expense', verbose_name='checker status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_maker',
            field=models.BooleanField(default=False, help_text='Designates whether the user can complete an expense.', verbose_name='maker status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
