# Generated by Django 4.2.5 on 2023-10-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bankcashout'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcashout',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
