# Generated by Django 4.2.5 on 2023-10-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bankcashout_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcashout',
            name='is_finished',
        ),
    ]
