# Generated by Django 4.2.5 on 2023-10-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_remove_bankcashout_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[['PT', 'Pretty Cash Account'], ['MW', 'MERCHANT ACCOUNT'], ['OT', 'OTHERS']], max_length=3),
        ),
    ]
