# Generated by Django 4.2.5 on 2023-10-04 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_bankaccount_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcashout',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashouts', to='bank.bankaccount'),
        ),
    ]
