# Generated by Django 4.2.5 on 2023-09-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
