# Generated by Django 4.2.5 on 2023-10-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='expense/'),
        ),
    ]
