# Generated by Django 4.2.5 on 2023-10-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bankcashout_is_finished'),
        ('expense', '0002_expense_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bank_cashout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='bank.bankcashout'),
        ),
    ]
