# Generated by Django 4.2.5 on 2023-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
