# Generated by Django 4.2.5 on 2023-09-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='quantity',
        ),
    ]
