# Generated by Django 4.2.5 on 2023-11-15 07:10

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction_code',
            field=models.CharField(default=secrets.token_hex, max_length=64, unique=True),
        ),
    ]
