# Generated by Django 4.2.5 on 2023-10-04 11:46

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_checker',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_maker',
        ),
    ]
