# Generated by Django 4.2.5 on 2023-10-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
