# Generated by Django 4.2.5 on 2023-10-18 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2FAAuth',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=lib.models.create_hex_token, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_tokens_2fa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'unique_together': {('user', 'token')},
            },
        ),
    ]
