# Generated by Django 4.2.5 on 2023-10-18 09:41

from django.db import migrations, models
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user2faauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2faauth',
            name='token',
            field=models.CharField(default=pyotp.random_base32, max_length=255),
        ),
    ]
