# Generated by Django 4.2.5 on 2023-10-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user2faauth_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user2faauth',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'User 2Factor Auth'},
        ),
    ]
